version: 3.0
services:
    atlas:
        container_name: atlas
        image: asd
        ports:
          - '5432:5432'
    dbpostgres:
        image: postgres
        restart: always
        ports:
          - '5432:5432'
        environment:
            POSTGRES_DB: mlflow_db
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: example
